In [ ]:
# creating a random tensor

In [2]:
import torch
import pandas as pd
import numpy as np

In [4]:
random_tensor = torch.rand(6, 8, 4)
random_tensor

tensor([[[0.0752, 0.1120, 0.3036, 0.6459],
         [0.6256, 0.2737, 0.8188, 0.6209],
         [0.2571, 0.9166, 0.3822, 0.6521],
         [0.3344, 0.7484, 0.3415, 0.5024],
         [0.0570, 0.2753, 0.7112, 0.4294],
         [0.3757, 0.3473, 0.5766, 0.6885],
         [0.6367, 0.2821, 0.0533, 0.8929],
         [0.9524, 0.0168, 0.6352, 0.0688]],

        [[0.7448, 0.5388, 0.4676, 0.7820],
         [0.3162, 0.2150, 0.2982, 0.4834],
         [0.3746, 0.5951, 0.9016, 0.4205],
         [0.9661, 0.4172, 0.0061, 0.6170],
         [0.6347, 0.2614, 0.3472, 0.1474],
         [0.3106, 0.1989, 0.8951, 0.6194],
         [0.9595, 0.4655, 0.9545, 0.9920],
         [0.8868, 0.8257, 0.4869, 0.0798]],

        [[0.0208, 0.8919, 0.3261, 0.7954],
         [0.3649, 0.8662, 0.7667, 0.1004],
         [0.8885, 0.9324, 0.7381, 0.1627],
         [0.1766, 0.8157, 0.6938, 0.9905],
         [0.2377, 0.6662, 0.7462, 0.8750],
         [0.3939, 0.0923, 0.2670, 0.7434],
         [0.5729, 0.7517, 0.8331, 0.5834],
       

Random tensors created =>
6 * 8 * 4 =
192

In [8]:
# creating random tensor equal to image tensor
random_image_tnsr = torch.rand(size=(224, 224, 3)) #height, width, colour
random_image_tnsr.shape, random_image_tnsr.ndim


(torch.Size([224, 224, 3]), 3)

In [16]:
ran_tnsr = torch.rand(2, 3, 4, 5)
ran_tnsr, ran_tnsr.ndim

(tensor([[[[0.2410, 0.0221, 0.8670, 0.3416, 0.4692],
           [0.0435, 0.8680, 0.5730, 0.8206, 0.5611],
           [0.3409, 0.8820, 0.5759, 0.4903, 0.5185],
           [0.9317, 0.3955, 0.2800, 0.0115, 0.2756]],
 
          [[0.4861, 0.7043, 0.1411, 0.8201, 0.7399],
           [0.8842, 0.8158, 0.2871, 0.1970, 0.5062],
           [0.1035, 0.3046, 0.4908, 0.0253, 0.5095],
           [0.4488, 0.4177, 0.8503, 0.2891, 0.8919]],
 
          [[0.0399, 0.3165, 0.1850, 0.7991, 0.4429],
           [0.5852, 0.3570, 0.9959, 0.7667, 0.0914],
           [0.1206, 0.4581, 0.7746, 0.9612, 0.8443],
           [0.5648, 0.8128, 0.4216, 0.9652, 0.3209]]],
 
 
         [[[0.0085, 0.5521, 0.5208, 0.2483, 0.3407],
           [0.0642, 0.3615, 0.3496, 0.9554, 0.2537],
           [0.6177, 0.8107, 0.3942, 0.9166, 0.1898],
           [0.4277, 0.2188, 0.3845, 0.8620, 0.2641]],
 
          [[0.6676, 0.2667, 0.3866, 0.9086, 0.9458],
           [0.6791, 0.5885, 0.6132, 0.9189, 0.5814],
           [0.4721, 0.6184, 0.4

In [23]:
# zeros and one, used for masking means which data we dont want the program to consider

ones = torch.ones(size=(3, 3))
zeros = torch.zeros(size=(3,3))
zeros, ones

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [34]:
# creating a range of tensors
one_to_10 = torch.arange(start=1, end=11, step=1)


# tensors-like

ten_0s = torch.zeros_like(input=one_to_10)
print("one_to_10's :", one_to_10), print("ten_0s :", ten_0s )

one_to_10's : tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
ten_0s : tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


(None, None)

In [36]:
# tensor data types

# single precision =  32 bits,  half precision = 16bit,  full precision = 64bits

#torch.float, torch.half, torch.double {floating points}

#tensor data types are one of the 3 major errors in PyTorch and Deep Learning
# 1. tensors not right datatypes
# 2. tensors not right shape
# 3. tensors not on right device

# finally important parameters of tensors are 1. dtype, 2.device, 3.requires_grad

Flot_tnsr = torch.tensor([3.0, 6.0, 9.0],
                         dtype=None, #-> wt dtype is tnsr
                         device=None, #-> wt device is ur tnsr ON
                         requires_grad=False) #-> track gradients or not with operations
Flot_tnsr

tensor([3., 6., 9.])

In [37]:
Flot_tnsr.dtype

torch.float32

In [40]:
#multipying 2 dtypes
flt = torch.tensor([3, 4, 5], dtype=torch.half)
fltt = torch.tensor([4, 5, 6], dtype=torch.float)

flt*fltt

tensor([12., 20., 30.])

In [42]:
some_tnsr = torch.rand(4, 3)

#finding details of tensor and resolving the errors (3)
print(some_tnsr)
print(f"Data type of tnsr : {some_tnsr.dtype}")
print(f"Shape of tnsr: {some_tnsr.shape}")
print(f"Device tnsr is on : {some_tnsr.device}")

tensor([[0.6310, 0.1961, 0.4654],
        [0.6824, 0.8888, 0.1429],
        [0.2103, 0.2797, 0.4188],
        [0.6582, 0.9830, 0.7026]])
Data type of tnsr : torch.float32
Shape of tnsr: torch.Size([4, 3])
Device tnsr is on : cpu


In [46]:
#manipulating tensors(tensor operations)

#operations
tnsr =torch.tensor([1, 2, 3])
tnsr + 10, #-> addition

(tensor([11, 12, 13]),)

In [48]:
tnsr - 4, #-> subtraction

(tensor([-3, -2, -1]),)

In [49]:
tnsr * 5 #-> multiplication

tensor([ 5, 10, 15])

In [52]:
# pytorch also have built-in functions for these operations
torch.add(tnsr, 10), torch.mul(tnsr, 15)

(tensor([11, 12, 13]), tensor([15, 30, 45]))

Multiplications in ML and Deep Learning
can be done in 2 ways
1. element-wise
2. matrix multiplications

In [55]:
#element wise multiplication
print(tnsr, "*" , tnsr)
print(f"Equals : {tnsr * tnsr}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [59]:
#-> Matrix multiplications ("dot product")
%%time
torch.matmul(tnsr, tnsr)


CPU times: user 498 µs, sys: 0 ns, total: 498 µs
Wall time: 429 µs


tensor(14)

In [ ]:
# conditions to satisfy
# @ inner dimension must match
# 1. (3,2) @ (3, 2) -> wont work
# 2. (3,2) @ (2, 3) -> will work
# 3. (2,3) @ (3, 2) -> will work
# @ Because resultant matrix has the to be the shape of outer dimensions

In [60]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.2423, 1.5852],
        [1.3304, 1.6688]])

In [65]:
tnsr_a = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])
tnsr_b = torch.tensor([[7, 10],
                      [8, 11],
                      [9, 12]])
torch.mm(tnsr_a, tnsr_b)
#we will get an error [mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)]

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [66]:
# to solve this inner dimension problem we use transpose
tnsr_b

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [67]:
#transpose [same elements are rearranged]
tnsr_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [71]:
# example
print(f"original shapes: tnsr_a = {tnsr_a.shape}, tnsr_b = {tnsr_b.shape}")
print(f"\nNew shapes : tnsr_a = {tnsr_a.shape}, tnsr_b = {tnsr_b.T.shape}")
print(f"\nmultipying: {tnsr_a} @ {tnsr_b.T}")
print(f"\n output : {torch.mm(tnsr_a, tnsr_b.T)}")


original shapes: tnsr_a = torch.Size([3, 2]), tnsr_b = torch.Size([3, 2])

New shapes : tnsr_a = torch.Size([3, 2]), tnsr_b = torch.Size([2, 3])

multipying: tensor([[1, 2],
        [3, 4],
        [5, 6]]) @ tensor([[ 7,  8,  9],
        [10, 11, 12]])

 output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Tensor aggrigation :
min, max, mean, sum, ect.

In [72]:
## Tensor aggrigation

#create tensor
x = torch.arange(0, 100, 10)

x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [73]:
#min
torch.min(x)
min(x)

tensor(0)

In [74]:
#max
torch.max(x)
max(x)

tensor(90)

In [77]:
torch.mean(x.type(torch.float)) # torch.mean requires a tensor of flot32 dtype

tensor(45.)

In [78]:
torch.sum(x)

tensor(450)

In [79]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [82]:
x.argmin() #minimum position value

tensor(0)

In [84]:
x[1] #2nd index value is 10

tensor(10)

notes of the todays learning : https://www.notion.so/01-Basics-487cd1e3489e4f31b5e2db052d9dc234?pvs=4